### ISSUE TITLE
question

### ISSUE THREAD

**Issue by XahidEx** [aycanogut/portfolio-next#16]
Bro, Did you use "test token" as RAINDROP_TOKEN? 
And second question is, what do I need to put in collection id? Because I've more than 1 collection.

**Comment by aycanogut** [comment]
Hey, sorry for late reply, and yes I used the test token for auth.
You can fetch all of your collections with this single endpoint. Just update your collection id.
'https://api.raindrop.io/rest/v1/raindrops/0?perpage=50&collectionId=yourCollectionID"

**Comment by aycanogut** [comment]
Hey @XahidEx,

I have found a new solution to fetching Raindrop API's. I used to fetch all the data from the API but it was not good for my scenario. I update the method to fetch for only relevant collection. You can find the example in [here](https://github.com/aycanogut/portfolio-next/blob/main/src/pages/bookmarks/index.tsx).
